- hosts: laravel
  become: true

  tasks:
  - name: For addin PPA 
    apt:
      name:
      - software-properties-common
      - gnupg-agent

  - name: Installing ppa repo
      apt_repository:
        repo: 'ppa:ondrej/php'
  
  - name: Update cache Apt
    apt:
      update_cache: yes
      cache_valid_time: 3600
      
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Install PHP
    apt:
      name:
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-curl
      - php7.2-gd
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-tokenizer
      - php7.2-json
      - php7.2-common
      - php7.2-xmlrpc
      - php7.2-soap
      - php7.2-intl
      - php7.2-zip
      state: present

  - name: Install MySQL Server
    apt:
      name: mysql-server
      state: present

  - name: Start MySQL Server
    systemd:
      name: mysql
      state: started
      enabled: yes
  
  - name: Install Composer
    apt:
      name:
      composer

  - name: Update nginx config
    copy:
      src: /config_nginx/site
      dest: /etc/nginx/sites-available/default
      owner: www-data
      group: www-data
    notify: Restart Nginx

  - name: Create simlink Nginx
      file:
        src: /etc/nginx/sites-available/laravel.conf
        dest: /etc/nginx/sites-enabled/laravel.conf
        state: link
      
  - name: clone laravel
      git:
        repo: https://github.com/laravel/laravel.git
        dest: /var/www/lavarel
    become: yes
  
  - name: set permission for lavarel folder
    file:
      path: /var/www/lavarel
      state: directory
      owner: www-data
      group: www-data
      recurse: yes
      mode: '0755'
    become: yes

 - name: Настройка прав на директорию проекта Laravel
      file:
        path: /var/www/laravel
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

  handlers:
  - name: Restart Nginx
    systemd:
      name: nginx
      state: restarted
