- hosts: laravel
  become: true

  tasks:
  - name: For addin PPA 
    apt:
      name:
      - software-properties-common
      - gnupg-agent

  - name: Installing ppa repo
      apt_repository:
        repo: 'ppa:ondrej/php'
  
  - name: Update cache Apt
    apt:
      update_cache: yes
      cache_valid_time: 3600
      
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Start Nginx
    systemd:
      name: nginx
      state: started
      enabled: yes

  - name: Install PHP
    apt:
      name:
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-curl
      - php7.2-gd
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-tokenizer
      - php7.2-json
      - php7.2-common
      - php7.2-xmlrpc
      - php7.2-soap
      - php7.2-intl
      - php7.2-zip
      state: present

  - name: Install MySQL Server
    apt:
      name: mysql-server
      state: present

  - name: Start MySQL Server
    systemd:
      name: mysql
      state: started
      enabled: yes
  
  - name: Install Composer
    apt:
      name:
      composer

  - name: Install lavarel
    apt:
      name:




  - name: Update nginx config
    copy:
      src: files/default
      dest: /etc/nginx/sites-available/default
      owner: www-data
      group: www-data
    notify: Restart Nginx

  handlers:
  - name: Restart Nginx
    systemd:
      name: nginx
      state: restarted
